info:
  name: Create Role
  type: http
  seq: 3

http:
  method: POST
  url: "{{baseUrl}}/api/v1/user-management/roles"
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "name": "NEW_ROLE",
        "description": "A new role"
      }
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
