info:
  name: Get Role
  type: http
  seq: 2

http:
  method: GET
  url: "{{baseUrl}}/api/v1/roles/:id"
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
