info:
  name: 4. Create Admin Config
  type: http
  seq: 4

http:
  method: POST
  url: "{{baseUrl}}/api/v1/admin-moderation/admin-configs"
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "key": "custom_config_key",
        "value": "custom_config_value",
        "description": "A custom configuration parameter created via API."
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
