info:
  name: Admin Get Settings
  type: http
  seq: 16

http:
  method: GET
  url: "{{baseUrl}}/api/v1/reels/admin/settings"
  auth:
    type: bearer
    token: "{{token}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
